# Generated by Django 5.0.6 on 2024-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='User_Type',
            field=models.CharField(choices=[('recruiter', 'Job Recruiter'), ('seeker', 'Job Seeker')], max_length=100, null=True),
        ),
    ]
